version: "3.7"
services:
  mariadb:
    image: ghcr.io/talokuntoon/tk-database:10.5.9
    command: --sql_mode=""
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - TZ="Europe/Helsinki"
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./mariadb-data:/var/lib/mysql:delegated
